unicef/inventory-hugo-theme

- .circleci/config.yml
- .circleci/deploy.sh
This commit creates a new CircleCI continuous integration pipeline to
build the example Hugo site, check that it uses valid HTML, and publish
the built site to GitHub Pages.
> ci: Add CircleCI pipeline to build and test site

- assets/css/style.css
@jwflory this PR handles the styling for issue [#14](https://github.com/unicef/inventory/issues/14) in the [inventory](https://github.com/unicef/inventory) repo.
PS: My vs code formatter kinda made changes throughout the css file. The changes I really made are from line 594.
> Make blockquotes more pretty and make citation more clear

- assets/css/style.css
This addresses [this issue](https://github.com/unicef/inventory/issues/32) and changes the color of hyperlinks to a darker shade to help
people with visual impairmants.
> assets: Change color to improve accessibility

- assets/css/style.css
- layouts/partials/default.html
- layouts/partials/header-link.html
This is to help enable easy link sharing to specific sections of the content. It addresses [this issue](https://github.com/unicef/inventory/issues/31)
> Show icon next to sub-headings.

- .github/ISSUE_TEMPLATE/01-bug.md
- .github/ISSUE_TEMPLATE/02-improvement.md
- .github/ISSUE_TEMPLATE/03-new.md
- .github/ISSUE_TEMPLATE/config.yml
This commit adds new issue templates for the Inventory Hugo theme.
Originally, I disabled issues on this repository to keep everything
together in a single repository. However, now that there are multiple
downstreams of this theme, it makes sense to use the issue tracker of
this repository to collect feedback about the design, features, and
UI/UX of the Hugo theme, separate from site-specific content.
> meta: Add issue templates

- layouts/partials/footer.html
- layouts/partials/navigation.html
This commit changes the references to "UNICEF Global" into strings
derived from the Hugo site configuration file. This makes the theme more
general-purpose and easier to adapt for other use cases, like the
SustainOSS open source + design knowledgebase prototype.
It also adds more localization flexibility for text in the footer.
Addressing @Idadelveloper's feedback in PR #39.
> :wrench: layouts: Use config-derived metadata for parent organization metadata

- assets/css/style.css
- layouts/partials/head.html
- layouts/partials/navigation.html
This commit adds a new config file value to give the site title in the
navigation bar a contrasting or matching color:
1. `head.html` now reads in `.Site.Params.text_title_color` from Hugo
config, adds to root stylesheet.
2. Site title in the navigation bar will use the custom text title color
from the config.
3. `a:focus` and `a:hover` changed to `var(--light-color)`
This addresses feedback from @Idadelveloper in PR #39 about color.
> :lipstick: Add custom color to site title for matching logo color

- README.md
- sample_config.yaml
This commit bundles a `sample_config.yaml` file, which can quickly be copied for use in a new site using this theme.
> :memo: docs: Add a sample configuration for a Hugo site

- exampleSite/i18n/en.yaml
- exampleSite/i18n/fr.yaml
- i18n/en.yaml
- i18n/fr.yaml
This commit takes the existing localization files from the example site
and embeds them into a directory where Hugo will look for localizations.
These can be overridden by creating a file of the same name in the Hugo
site, but would require copying all existing translations from the
upstream-provided file. Updates and changes would be manually managed.
This encourages upstreaming of localization efforts and also avoids
snags when a new site is launched with this theme, but the parts of the
theme expecting a `i18n/` configuration render empty.
> :globe_with_meridians: i18n: Bundle localization into theme

- assets/css/style.css
- layouts/partials/default.html
In sidebar.html we used section-tree-nav template which is overlapping with the one in the default.html and this is causing the issue #49 . So i changed the template name in default.html.
> changed section-tree-nav template name in default.html

- layouts/partials/navigation.html
This commit fixes a bug where the UNICEF Blue was hard-coded into the
navigation bar, and changes that hard-coded value to use the primary
color set by the site maintainer in the Hugo config file (`params.`
`primary_color`).
Additionally, I changed the color for the translations options to use a
white color, since it is hard to read when the primary color is a darker
color.
> :lipstick: layouts(navigation): Use consistent color on all pages

- assets/css/style.css
- data/dpg_standards.yaml
- layouts/_default/dpg-report.html
- layouts/partials/dpg-report.html
- layouts/partials/head.html
This commit creates a new custom layout for DPG report cards in the
UNICEF Inventory theme. DPG report cards are at-a-glance views of a
Venture Fund company's progress in meeting the DPG Standard.
More context about this change is in unicef/coach#1. This commit should
be merged once the idea is validated and the early prototyping phase is
complete.
> :new: :lipstick: layouts: Add dpg-report layout (see unicef/coach#1)

- exampleSite/content/installation/configuration/_index.en.md
- exampleSite/content/installation/elements/_index.en.md
- exampleSite/static/pdfs/sample.pdf
- layouts/shortcodes/embed-pdf.html
I have added demo of this shortcode in  _installation/configuration_  page .
For using this Shortcode we have to pass the Name of the pdf into the shordcode as shown in the demo.
The pdfs should be stored in the static/pfds folder.
Fixes #33.
> Added embed-pdf shortcode

- layouts/partials/default.html
This commit partially fixes issue #30. The reason I've submitted it as a partial fix is because, the referenced issue doesn't seem to just affects pages inside this repository but also pages inside the cohorts directory located inside this themes' parent directory .i.e. `unicef/inventory`. I will submit a separate pull request on the parent directory to fix the issue there.
> Add condition to only show "RA Section" when there's content available

- assets/css/style.css
- exampleSite/config.yaml
Fixes #62
Changes:
This PR resolves the styling issue previously faced while using the `highlight` function to create code blocks.
Screenshot of the change:
> 🐛 fix: Improved styling of highlight code blocks

- layouts/partials/dpg-report.html
The PDF download button logic was moved into a partial after this layout
was created. This refactors to use the partial and maintain less code.
> :recycle: layouts(dpg-report): Reuse download-pdf partial

- exampleSite/config.yaml
Fixes #57
In Footer partial, we have this-
```html
<li><a class="nav-link text-white" href="{{ site.BaseURL | relLangURL }}">HOME</a></li>
{{ range site.Menus.main }}
{{if ne .Name "pages"}}
<li class="nav-item">
<a class="nav-link text-white text-uppercase" href="{{ .URL | absLangURL }}">{{ .Name }}</a>
</li>
{{ end }}
{{ end }}
```
In all other upstreams we dont have Home in the Menu array but we do have it in the exampleSite. This is what causing the duplication in exampleSite. So, i have removed it from config file of exampleSite.
@jwflory I contacted the Assignee he said i can proceed.
> Removed Duplicate Home Link in Footer

- README.md
An example configuration used to be bundled at the top of the repo, but
now it is included as part of the example site used in building this
theme. This commit fixes the broken link in the README.
Closes #79.
> :bug: :memo: README: Fix link for example site config

- assets/css/style.css
- exampleSite/content/installation/elements/_index.en.md
- exampleSite/content/installation/elements/_index.fr.md
Fixes #64 and #66 
Changes:
The PR adds shortcodes for `CAUTION` and `IMPORTANT` admonition blocks.
Screenshot of the change:
To test if the new admonitions are properly working, the following code can be used: 
```
{{< notice important >}}
This is a simple important.
{{</ notice >}}
{{< notice caution >}}
This is a simple caution.
{{</ notice >}}
```
> 💄 fix: Added shortcodes for CAUTION and IMPORTANT admonition

- exampleSite/content/installation/elements/_index.en.md
- exampleSite/content/installation/elements/_index.fr.md
Fixes #71
Changes:
This PR adds `table` shortcodes to the existing tables along with the documentation to the [elements page](https://unicef.github.io/inventory-hugo-theme/installation/elements/). 
Screenshot of the change:
> 📝 docs: Added table shortcode in Elements page

- exampleSite/content/billing-pricing/bill/_index.en.md
- exampleSite/content/installation/customization/_index.en.md
- layouts/partials/default.html
fixes #15
Here is a demo-
Note:
To use this feature,
- We should add `author` attribute to frontmatter.
- We can also add `authorEmail` attribute for displaying their email address
> added author byline

- exampleSite/config.yaml
I have checked out all the websites which are using this theme and i found out that except [SustainOSS Design & UX knowledgebase](https://sustainers.github.io/design/) all others are using the same colour pallete.
So, i thought of adding the same colour pallete to the exampleSite, so that it will be easier to inspect design issues and fix it.
> changed colour variables

- exampleSite/config.yaml
- exampleSite/content/features/redirect.en.adoc
- i18n/en.yaml
- i18n/fr.yaml
- layouts/redirect/single.html
This commit adds a new type of layout, a redirect, to the theme. A
redirect layout is similar to the existing Hugo aliases, except instead
of being limited to internal redirect (i.e. redirecting one page to
another page in the same site), we can now redirect a user to a page
hosted externally on another site.
The motivation for this is so that we can ensure that user experience is
not disrupted when content is moved from one site to somewhere else. In
our case, we want to move content about data science into the UNICEF
Data Science & A.I. Toolkit and some of our developer-focused content
into the Software Development Toolkit. This new feature enables that
transition to happen smoothly for anyone who has an old URL bookmarked
or linked somewhere else. See unicef/inventory#128 for more …
> :sparkles: layouts: Add redirect layout and docs (closes #69)

- README.md
Reorder some of the attribution credits into a list of toolkits. Add the
UNICEF Data Science & A.I. Toolkit as another example of a site using
this theme.
ref: https://github.com/unicef/ooi-toolkit-ds
> :memo: README: Add attribution note for Data Science & A.I. Toolkit

- exampleSite/content/contributing/_index.en.md
- exampleSite/content/contributing/stakeholders.en.adoc
This commit adds a new "Contributing" category to the site and
initializes it with a "Key stakeholders" page. The stakeholders page is
part of a user story and defines the primary users for the Open Source
Inventory toolkit.
This page is part of a gradual effort of converting the example site for
the UNICEF Inventory theme into more comprehensive and useful
documentation. Eventually, more content may be migrated to live in this
category as a common reference for several toolkits.
Closes #127. Part of #89.
> :new: :memo: Add contributing category & key stakeholders (closes #127)

- layouts/partials/default.html
This fix is useful for dpg indicators restructure.
If there is no content in a particular DPG indicator then this change will show the description of that page there.
Results:
> Added description to the content

- assets/css/style.css
- exampleSite/config.yaml
- layouts/partials/navigation.html
Fixes #143 
I have modified the logo of the Inventory-Hugo theme site to make it consistent with the inventory and made it responsive in mobile devices.
This is how the new change looks-
In mobile:
In desktop:
> made Navbar responsive

- layouts/index.html
This commit changes the site homepage layout so that any page with the
layout "dpg-standard" will also show on the homepage, along with the
pages tagged as "type: docs" in the post front-matter.
Closes unicef/inventory-hugo-theme#128.
> DPG indicators layout update

- exampleSite/content/features/brand-identity/_index.en.adoc
The theme no longer supports the alternative logo feature. It is only possible to provide one logo. This commit updates the documentation to accurately describe the current state of the theme.
> :bug: :memo: docs(brand-identity): Describe using one logo, not two

- layouts/index.html
This commit shows the "team" template type on the index page of the site. The use case for this change is so that the total cohorts view still appears when navigating to `/inventory/cohorts/` and it also appears as its own category on the site homepage alongside other topics.
This contributes to unblocking unicef/inventory#136.
> :bug: layouts(index): Show "team" type posts on index page

- assets/css/style.css
- exampleSite/content/about/lorem-ipsum.en.adoc
- exampleSite/content/contributing/stakeholders.en.adoc
- exampleSite/content/features/_template.en.adoc
- exampleSite/content/features/admonitions/_index.en.adoc
- exampleSite/content/features/author-byline/_index.en.adoc
- exampleSite/content/features/brand-identity/_index.en.adoc
- exampleSite/content/features/code-highlighting/_index.en.adoc
- exampleSite/content/features/redirect/_index.en.adoc
- exampleSite/content/features/tab-tables/_index.en.adoc
- layouts/partials/default.html
- layouts/partials/page-tags.html
Fixes #123 
Tags can be added by specifying tags in the page description. For Example: 
```
title: Brand & identity
description: Change text and visual appearance to better represent the brand and identity of the site owner.
categories: features
tag: ["design", "brand", "identity"]
downloadBtn: true
```
> Added displaying Page Tags functionality

- theme.toml
The theme configuration file incorrectly used quotes. This fixes the error message reported by the Hugo server when building a site with the bad syntax. This will also fix validation errors that the Hugo Themes site may have in processing information about the UNICEF Inventory theme.
> :bug: theme.toml: Fix TOML syntax error
