unicef/inventory-hugo-theme

- layouts/partials/default.html
This adds a section to display related articles.
> PR for #12  Highlight related articles at the bottom of each article. 

- layouts/partials/breadcrumb.html
- layouts/partials/default.html
Signed-off-by: Ida Delphine <idadelm@gmail.com>
> layouts: Add breadcrumb navigation

- assets/css/style.css
- layouts/partials/head.html
> Show big quotes for citation

- assets/js/script.js
- layouts/partials/default.html
- layouts/partials/head.html
This PR resolves this [issue](https://github.com/unicef/inventory/issues/33).
> Export an article to pdf

- assets/css/style.css
- layouts/_default/baseof.html
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/index.html
- layouts/partials/alert.html
- layouts/partials/default.html
This tackles https://github.com/unicef/inventory/issues/41
> layouts: Add announcement feature to all pages

- assets/css/style.css
- layouts/partials/navigation.html
> Adjust UNICEF global link on mobile

- assets/css/style.css
@jwflory this complements t[his commit](https://github.com/unicef/inventory/pull/111/commits/5f2c63857d59e5594cd29f6f94b68b0d46cd439e) in this [PR](https://github.com/unicef/inventory/pull/111).
> Make profile cards display properly on smaller screens

- assets/css/style.css
- layouts/partials/navigation.html
@jwflory this addresses #36 
Looks better
> Adjust nav bar on mobile devices

- assets/css/style.css
@jwflory this adjusts the extra spacing in the sidebar of the cohort pages
> Adjust sidebar scroll spacing

- assets/css/style.css
- layouts/index.html
- layouts/partials/default.html
- layouts/partials/download-pdf.html
- layouts/partials/footer.html
Made following changes :
1. The sidebar when scrolled is getting cropped something like this-
So i changed it by increasing the top length
2. Cards in the index page when hovered looks something like this-
As the card already had box shadow and cursor pointer, i removed the underlining for better UI
3. Added some padding to the breadcrumb
4. Added margin-top to the footer for better spacing in between content box and footer
> Changed some css for better UI.

- assets/css/style.css
- layouts/partials/head.html
> Make Table of Contents more appealing and responsive 

- .github/CONTRIBUTING.md
- README.md
This commit adds new contributing guidelines for the UNICEF Inventory theme. It includes four main topics:
1. Contribution process (a.k.a. governance)
2. Conventions & courtesies
3. Structure & components
4. How to create a developer environment
> :new: :memo: .github: Add contributing guidelines

- assets/css/style.css
- exampleSite/config.yaml
- layouts/partials/head.html
Fixes #90 
- Code
- User Interface
> Highlight the background color of buttons while hovering.

- assets/css/style.css
- assets/js/script.js
- exampleSite/config.yaml
- i18n/en.yaml
- i18n/fr.yaml
- layouts/partials/default.html
> added edit-this-page btn

- assets/css/style.css
- layouts/partials/types.html
Fixes #102 
**before** -
**after** -
> changed layout of startup cards

- layouts/partials/cohorts.html
> added sidebar in cohorts page

- assets/css/style.css
This is how the cards look after changing the colors as in PR #116 and adding border-radius
According to me, this already looks great.
However, we can improve it more by 
1. Using Designed illustrations or images in place of icons.
2. Adding a button in the card ( This is for mobile UI/UX improvement as there will not be any hover state in mobile. So, there is a chance that user will not recognize it as a link)
@jwflory what do you suggest?
> card UI improvement

- assets/css/style.css
> primary btn hover fix

- assets/css/style.css
- layouts/partials/breadcrumb.html
@jwflory couldn't figure out why the checks are failing.
This is related to the link, can you say what exactly I have to change?
> Used hugo in breadcrumb bar functionality instead of javascript

- layouts/partials/cohorts.html
- layouts/partials/types.html
> Modified cohorts and types partials to make it uniform with the theme.

- layouts/partials/cohorts.html
Fixes #130 
I have added Facebook and Instagram. Is there anything more we should add?
> added more social media platforms

- layouts/partials/navigation.html
> removed hyperlink for unicef logo
